version: "3"
services:
  rabbitmq:
    image: "rabbitmq:3.13-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 30s
      retries: 3
  
  audio-recorder:
    build: ./audio-recording-app
    ports:
      - "3000:3000"
    volumes:
      - ./audio-recording-app:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://audio-service:8081/api/v1

  audio-service:
    build: audio-service/
    ports:
      - "8081:8081"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker:
    build: audio-service/
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: "npx tsx src/worker.ts"
